server:
  port: 9002
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        # 换成nginx的1111端口,做集群
        server-addr: 192.168.1.133:1111
      # server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'