server:
  port: 80

# 服务别名-----注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      connect-string: 192.168.1.127:2181 # 虚拟机ip地址
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3307/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 200004
    druid:
      validation-query: select 1
      test-while-idle: true