server:
  port: 80

spring:
  application:
    name: cloud-consumer-hystrix-feign-order

# 注册到 eureka中心
eureka:
  client:
    # 注册进 Eureka 的服务中心
    register-with-eureka: false
    service-url:
      # 设置与 Eureka Server 交互的地址
      # defaultZone: http://localhost:7001/eureka/
      # 集群版配置
      # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      #单机版
      defaultZone: http://eureka7001.com:7001/eureka/

# 支持Hystrix
feign:
  hystrix:
    enabled: true
